- prefix: /svc # default for all services
  totalTimeoutMs: 500
- prefix: /svc/foo
  totalTimeoutMs: 1000 # overrides the default from above
- prefix: /svc/bar
  # applies only to the /svc/bar service
  retries:
    budget:
      minRetriesPerSec: 5
      percentCanRetry: 0.5
      ttlSecs: 15
    backoff:
      kind: jittered
      minMs: 10
      maxMs: 10000
